name: Deploy Angular app to GitHub Pages (docs folder)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app with output to docs/
        run: npx ng build --output-path docs --base-href /Wade-s-Wine-Watcher/

      - name: Copy index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Commit and push docs to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Angular app to docs folder for GitHub Pages" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
